# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Principal
    url: /#top
    weight: 10
  - name: Solução
    url: /#solucao
    weight: 20
  - name: Sobre Nós
    url: /#sobre
    weight: 30
  - name: Fale Conosco
    weight: 60
    url: /#contato
  - name: Blog
    weight: 40
    url: blog/
  
    #hasChildren: true
  #- parent: Resources
  #  name: Blog
  #  url: blog/
