# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Principal
    url: /#principal
    weight: 10
  - name: Solução
    url: /#features
    weight: 20
  - name: Sobre Nós
    url: /#sobre
    weight: 30
  - name: Blog
    weight: 40
    url: blog/
  - name: Fale Conosco
    weight: 60
    url: contato/
    #hasChildren: true
  #- parent: Resources
  #  name: Blog
  #  url: blog/
