# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Companhia
    local_business_type: ''
    org_name: ''
    description: 'Criação automática de atividades educacionais.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "learnice.svg"
    button:
      enable: true
      text: "Quero Usar"
      url: "https://hugoblox.com/templates/"
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: '© {year} Learnice. Todos os direitos reservados.'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
